spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cars_group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

#spring.json.trusted.packages: "*"
# org.springframework.kafka.support.serializer.JsonDeserializer